bart parameters
tidymodels/dials pull request #191
Opened 2021-09-30 17:07 UTC by topepo

2021-09-30 17:15 UTC, hfrick requested changes

2021-09-30 17:15 UTC, hfrick commented on NEWS.md
> +  1`parsnip::bart()`.
```suggestion
  `parsnip::bart()`.
```

2021-09-30 17:15 UTC, topepo commented
😞

2021-09-30 17:15 UTC, hfrick commented
Looks good, just a typo which needs a re-doc!

2021-10-01 09:12 UTC, hfrick approved these changes

2021-10-01 09:12 UTC, merged