move `mtry_prop` from rules to dials
tidymodels/dials pull request #233
Opened 2022-05-10 15:18 UTC by simonpcouch

So that bonsai need not take on a rules dependency for this parameter!

Bumping version so we can require a specific dev version of this package in `rules`. Will be accompanied by a PR to rules shortly. :)

2022-05-10 18:09 UTC, simonpcouch commented
Update: I don't think bonsai actually needs to make use of the `mtry_prop` parameter. Leaving this and tidymodels/rules#54 open in case it's otherwise helpful to make this switch, but feel free to close if not!

2022-05-11 09:47 UTC, hfrick commented
have we settled on the API where the default is mtry is a count but you can switch to a proportion with `counts = FALSE` in `set_engine()`? (as you did for lightgbm, and already has been done for xgboost)

If so, would it make sense to switch `rules` over to that API as well? It would be nice to have a consistent approach if it's the same problem. cc @topepo

2022-05-24 13:35 UTC, hfrick requested changes
I spoke with Max and the plan is now:
* update rules to use the counts API https://github.com/tidymodels/rules/issues/55
* move `mtry_prop()` from rules to dials so it's still usable/maintained but add a note that our convention is to use counts and encourage people to use that as well when developing extensions.

Could you add such a note, please?

2022-05-24 13:35 UTC, hfrick commented on R/param_mtry_prop.R
> +#' [`xgboost`][parsnip::xgb_train()] (as `colsample_by*`).
update/remove this please

2022-05-24 13:35 UTC, hfrick commented on NEWS.md
> +  as a proportion rather than a count in tree-based models (@simonpcouch, #233).
I think in practice we only add the PR author here if they are not part of the team already but you're welcome to keep it in!

2022-05-25 09:26 UTC, hfrick approved these changes

2022-05-25 09:26 UTC, merged